name: Publicar en Bluesky cada 4h

on:
  schedule:
    - cron: '0 */4 * * *'   # Cada 4 horas UTC
  workflow_dispatch:        # También puedes lanzarlo manualmente

jobs:
  post-to-bluesky:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install @atproto/api

      - name: Ejecutar bot
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          BSKY_SERVER: ${{ secrets.BSKY_SERVER }}
          CTA_LINK: ${{ secrets.CTA_LINK }}
        run: node index.js
